---
title: "MCMC estimator"
author: "Montana McLeod"
date: "8/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library & Working directory
```{r}
library(rstan)
library(MASS)
library(densityratio)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

setwd("~/Documents/THESIS/Code")
load("./Data/Random_hypoxia.Rdata") #remove /.Data/
```


# Generate a random simulation 
```{r}
n= 1000 #no. of simulations  
sim <- data.frame( trawl = seq(1, n, by=1), 
                  pres = rep(NA, n), 
                  hypox = rand) #pulls a random sample from WCGBTS
 
#Severe hypoxia as logistic regression w/ 0.965 as midpoint of hypoxia 
  sim$p <- 1/ (1+exp(-(sim$hypox-0.965)))
plot(p~hypox, sim )

sim$p = ifelse(sim$hypox <= 0.5, 0.5, sim$hypox / (max(sim$hypox) + 0.001) ) #sets dep. on severe hypoxia to prob. of 0.1

sim$pres <- rbinom(nrow(sim), 1, sim$p) #random presence/absence
write.csv(sim,"simulated_data.csv", row.names = F) 
```


```{r}
# Logistic fxn for adding covariates 
logit <- function(mu) {log(mu/(1-mu))}

#inverse for transformation 
inv_logit <- function(mu) {
  exp(mu)/(exp(mu) + 1) }

# Set standards
psi = 0.9 #prob. of occupation
p = 0.25 # prob. of detection
hypoxia.p <- 0.01 # variation for hyopixa 

p.full <- inv_logit(logit(p) + hypox.p * hypox)

enc <- rbinom(n.samp,1,0.5) * rbinom(n.samp, 1, p.full)

```

# MLE - Optim functions
```{r}
#MLE Fxn included for covariates
hypoxia_optim <- function(beta, enc, trials, hypox){
  psi <- expit(beta[1]) #prop. of occ. sites
  P1 <- expit(beta[2] + hypox * beta[3])  #detc. prob.
  ### logit link function incorporating HYPOXIA as a covariate
  nLL = sum(-log((1 - psi)* dbinom(enc, trials, 0) + psi* dbinom(enc, trials, P1)))
}

```


# Initial values 
```{r}
beta <- c(psi = 0.9, p1 = 0.25, sigma = 0.01) 
```

# MLE fits
```{r}
sim_optim <- optim(beta, hypoxia_optim, enc = df$pres, trials = 10, hypox = df$hypox)
#expit(sim_out$par)  ## parameters are p , psi and sigma  

#extract parameters
sim_extract <- with(sim_optim, c(par[1], par[2], par[3]))
```



# Format Datasets as list for STAN
```{r}
sim_data <-  list(n.obs = nrow(df),
                    trials = rnorm(1, 10, 8),
                    enc = as.vector(df$pres),
                    hypox = as.vector(df$hypox))

```


# initial values
```{r}
inits <- function(chain_id){
  Ghyp <- rbeta(sim_extract[1:2],???? )
  list( 
    ) } #put intital values for params here
```


# Invoking STAN
```{r}
sim_fit <- stan(model_code = Hypoxia.stan,
            	          data = sim_data,
            	        chains = 1,
            	        warmup = 500,
            	          iter = 750,
            	          #init = inits, #may need to be species specific 
            	       control = list(adapt_delta = 0.95))
### START with one chain then if plot looks good go to 4
```


# Extract Stan
```{r}
<- rstan::extract()
``` 


#Visualizations of model fit
```{r}
pairs(occ.mvn.LKJ.stan)
traceplot(sim_fit)
trankplot(sim_fit) #might be in rethinking library?
```


