---
title: "WCGBTS_Data_Analysis"
author: "Montana McLeod"
date: "7/8/2020"
output: html_document
---

```{r setup, include=FALSE}
require("knitr")
opts_knit$set(root.dir = "~/Box Sync/McLeod_thesis/Code")
```

```{r}
library(ggplot2)
library(viridis)
library(dplyr)
library(lubridate)
library(tidyr)
```


# Raw Data
```{r}
sp_dat <- read.csv("../Data/Species.csv", stringsAsFactors = FALSE) #ALL data btw 2009-2019 of ALL species
  sp_data <- sp_dat[ ,c(3,5:6,8,17:18,21)] # only the important variables
  sp_data$year <- as.numeric(sp_data$year)
  sp_data <- sp_data[order(sp_data$year), ] # order the data set by Year
  
 
haul_data <- read.csv("../Data/Haul.csv", stringsAsFactors = FALSE)
  haul_data <- haul_data[ ,c(1:5,9:11)]
  haul_data <- haul_data[order(haul_data$year), ]
  colnames(haul_data)[colnames(haul_data) == "date_yyyymmdd"] <- "Date" #change name of date
  
Total_sp_data <- merge(sp_data, haul_data, by = c("trawl_id", "year",  "latitude_dd", "longitude_dd"), all = TRUE)  # merge data to be both datasets
Total_sp_data$Date <- as.Date(as.character(Total_sp_data$Date), format="%Y%m%d") #FORMAT DATE 

Total_sp_data <- Total_sp_data %>% 
  mutate(Month = factor(
    month(Date, label = FALSE),   # thing you're converting
    1:12,                                  # values it could take
    labels =                               # how they should appear
      c("January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"),
    ordered = TRUE)) #Sets the Month to automatically order via month order [lubridate package]

Total_sp_data <- Total_sp_data[ ,c(1,8,2,12, 3:7, 10:11)] #reorganize 
Total_sp_data <- Total_sp_data[Total_sp_data$year != 2009, ] #remove year w/0 lengths
```


# Datasets by species
```{r}

#GREENSTRIPED ROCKFISH
Grock <- subset(Total_sp_data, common_name == "greenstriped rockfish", select = c(trawl_id : longitude_dd, length_cm : temperature_at_gear_c_der) )
Grock <- Grock[Grock$sex == "F",]
table(Total_sp_data$common_name) #check no. of datapoints match with new DF

#YELLOWTAIL ROCKFISH
Yrock <- subset(Total_sp_data, common_name == "yellowtail rockfish", select = c(trawl_id : longitude_dd, length_cm : temperature_at_gear_c_der) )
Yrock <- Yrock[Yrock$sex == "F",]

#LINGCOD
Lingcod <- subset(Total_sp_data, common_name == "lingcod", select = c(trawl_id : longitude_dd, length_cm : temperature_at_gear_c_der) )
Lingcod <- Lingcod[Lingcod$sex == "F",]

#DOVER SOLE
Dsole <- subset(Total_sp_data, common_name == "Dover sole", select = c(trawl_id : longitude_dd, length_cm : temperature_at_gear_c_der))
Dsole <- Dsole[Dsole$sex == "F",]
```

# make a presence/ absence column
```{r}
#species of interest
zz <- Total_sp_data %>% 
  filter(common_name == c("Dover sole", "greenstriped rockfish", "lingcod", "yellowtail rockfish")) %>% 
  filter(sex == "F") # only females SS params 

# sp. density per trawl 
x <- zz %>% 
  group_by(trawl_id, common_name) %>% 
  summarise(count = n()) 

#record hypoxia per trawl
 xx <- zz %>% 
    group_by(trawl_id, Date) %>% 
    summarise(mean_hyp = mean(o2_at_gear_ml_per_l_der))
  
 zzz <- inner_join(xx, x) 
 
# set species as level to report them each time
zzz$common_name <- as.ordered(zzz$common_name)
levels(zzz$common_name) = c("Dover sole", "greenstriped rockfish", "lingcod", "yellowtail rockfish")

# return total combination of 4 species for each trawl ID
all <- zzz %>% 
expand(trawl_id, common_name)


# join all posibilties to df
z <- zzz %>% dplyr::right_join(all)
z <- z %>% fill(Date:mean_hyp)
z$Presence <- ifelse(is.na(z$count), 0, 1) #present/ absent 
z$count <- ifelse(is.na(z$count), 0, z$count) # 0 for no observation

#Reorder by date
  index <- with(z, order(trawl_id, common_name)) #organizes by month then year
  Spe_present <- z[index,]
  
  
  
#save(list= c("Grock", "Yrock", "Lingcod", "Dsole", "Spe_present") ,file= "../Data/Groundfish.Hyp.Rdata")
```

```{r}
#species of interest
 z <- Total_sp_data[!is.na(Total_sp_data$o2_at_gear_ml_per_l_der), ] # remove sample dates wehre NA is recorded for DO

 zz <- z %>% 
  filter(common_name == c("Dover sole", "greenstriped rockfish", "lingcod", "yellowtail rockfish")) %>% 
  filter(sex == "F")    # only females of our sp.

 Nact_hypox  <- z %>% 
   group_by(trawl_id, Date) %>% 
    summarise(mean_hyp = mean(o2_at_gear_ml_per_l_der)) # take avg DO value for each trawl b/c some collected multiple pts
  

```



# Prepare Dataset from WCGBTS
```{r}

source("./Library/params.R")
   Sp_selex <- read.csv("../Data/Sp.selex.csv") 
   load("./Results/Expected_Fishing_rate.Rdata") #from the SPR vs fishing values ## F priors
   load("../Data/Groundfish.Hyp.Rdata")
   mesh=200
   
   # Need a vector of size bins for historgram
   pars <- params("Dsole")
   meshmax = pars$Linf * 2
   x_D <- seq(from = 1, to = meshmax, length.out = mesh)
   pars <- params("Grock")
   meshmax = pars$Linf * 2
   x_G <- seq(from = 1, to = meshmax, length.out = mesh)
   pars <- params("Yrock")
   meshmax = pars$Linf * 2
   x_Y <- seq(from = 1, to = meshmax, length.out = mesh)
   pars <- params("Lingcod")
   meshmax = pars$Linf * 2
   x_L <- seq(from = 1, to = meshmax, length.out = mesh)
   
   
# x is the vector from params()
act.data <- function(data, source.dat, x){
  trawls <- unique(source.dat$trawl_id) # should be 3586 (8/27)
  Nact <- matrix(-999, nrow = length(x), ncol = length(trawls)) # store new dataset aggregrated across trawls and size densitites 
  
  for (w in 1:length(trawls)){
    h.dat <- hist(data[data$trawl_id == trawls[w], 7], breaks= c(x,Inf), plot = F)$count # creates densities by trawls
    Nact[,w] <- h.dat 
  
    #BELOW IS FOR DENSITY REQUIREMENTS BUT WE NEED COUNTS(?)
    # report trawl-ids as NA not as 0 present
    #for(n in 1:length(x)){
    #if(is.nan(Nact[n,w]) | is.na(Nact[n,w])){
    #Nact[n,w] <- 0
     #}
   # }
  }
  
  return(Nact)
}

 Nact_Dsole <- act.data(Dsole, Nact_hypox, x_D)  #round () if density
 Nact_Grock <- act.data(Grock, Nact_hypox, x_G)  #round () if density
 Nact_Yrock <- act.data(Yrock, Nact_hypox, x_Y) #round () if density 
 Nact_Lingcod <- act.data(Lingcod, Nact_hypox, x_L) #round (,2) if density

#save(Nact_Dsole, Nact_Grock, Nact_Yrock, Nact_Lingcod, Nact_hypox, file = "../Data/Hist_Spp.Rdata")
#Nact_Grock <- act.data(Grock, Spe_present)
```


# Greenstriped rockfish Distributions
```{r}
 ggplot(Grock, aes(x=length_cm, fill=as.character(year))) +
    geom_histogram(binwidth= 2)+ 
    facet_wrap(~Month, nrow=2)+ #separates the graphs by month
    scale_fill_brewer(palette = "Accent") 

#adding a column that classifies hypoxia 
Grock$Hypoxia <- ifelse(Grock$o2_at_gear_ml_per_l_der <= 0.504, "severe_hypoxia",
                      ifelse(Grock$o2_at_gear_ml_per_l_der > 0.5 & Grock$o2_at_gear_ml_per_l_der                        <=  1.43,"hypoxic", 
                        ifelse(Grock$o2_at_gear_ml_per_l_der > 1.43, "non-hypoxic", NA) ) )

ggplot(Grock[Grock$year %in% 2009 : 2015,], aes(Month, o2_at_gear_ml_per_l_der)) +
  geom_point(aes(color = Hypoxia)) +
  facet_wrap(~sort(year))

```


# Yellowtail rockfish Distributions 
```{r}
 ggplot(Yrock, aes(x=Month_no, fill=length_cm))+
    geom_histogram(binwidth= 0.5)+
   facet_wrap(~sort(year)) 
summary(Yrock)

#adding a column that classifies hypoxia 
Yrock$Hypoxia <- ifelse(Yrock$o2_at_gear_ml_per_l_der <= 0.504, "severe_hypoxia",
                      ifelse(Yrock$o2_at_gear_ml_per_l_der > 0.5 & Yrock$o2_at_gear_ml_per_l_der                        <=  1.43,"hypoxic", 
                        ifelse(Yrock$o2_at_gear_ml_per_l_der > 1.43, "non-hypoxic", NA) ) )

ggplot(Yrock, aes(Month_no, o2_at_gear_ml_per_l_der)) +
  geom_point(aes(color = Hypoxia)) +
  facet_wrap(~sort(year))
```


# Lingcod Distributions
```{r}
 ggplot(Lingcod, aes(x=Month_no, fill=length_cm))+
    geom_histogram(binwidth= 0.5)+
   facet_wrap(~sort(year)) 
summary(Lingcod)

#adding a column that classifies hypoxia 
Lingcod$Hypoxia <- ifelse(Lingcod$o2_at_gear_ml_per_l_der <= 0.5, "severe_hypoxia",
                      ifelse(Lingcod$o2_at_gear_ml_per_l_der > 0.5 & Lingcod$o2_at_gear_ml_per_l_der                        <=  1.43,"hypoxic", 
                        ifelse(Lingcod$o2_at_gear_ml_per_l_der > 1.43, "non-hypoxic", NA) ) )

ggplot(Lingcod, aes(Month_no, o2_at_gear_ml_per_l_der)) +
  geom_point(aes(color = Hypoxia)) +
  facet_wrap(~sort(year))
```


# Dover sole Distributions
```{r}
 ggplot(Dsole, aes(x=Month_no, fill=length_cm))+
    geom_histogram(binwidth= 0.5)+
   facet_wrap(~sort(year)) 
summary(Dsole)

#adding a column that classifies hypoxia 
Dsole$Hypoxia <- ifelse(Dsole$o2_at_gear_ml_per_l_der <= 0.5, "severe_hypoxia",
                      ifelse(Dsole$o2_at_gear_ml_per_l_der > 0.5 & Dsole$o2_at_gear_ml_per_l_der                        <=  1.43,"hypoxic", 
                        ifelse(Dsole$o2_at_gear_ml_per_l_der > 1.43, "non-hypoxic", NA) ) )

ggplot(Dsole, aes(Month_no, o2_at_gear_ml_per_l_der)) +
  geom_point(aes(color = Hypoxia)) +
  facet_wrap(~sort(year))
```

# calculate densities 
```{r}
dat <- as_tibble(Grock)
GRdens <- dat %>%
  filter(year <= 2015) %>% 
  group_by(Date) %>%
  summarise(density = n())
GRdens

GRhyp <- dat %>% 
   filter(year <= 2015) %>% 
  group_by(Date) %>%
  summarise(Mean_hyp = mean(o2_at_gear_ml_per_l_der))

# density with mean hypoxia 
GRden <- inner_join(GRdens, GRhyp)
GRden <- na.omit(GRden)

GRden.lm <- lm(density ~ -1 + Mean_hyp, data = GRden)
hist(resid(GRden.lm), xlab='residuals',main='',col="blue")
summary(GRden.lm)

# glm of poisson dist.
Grock.glm <- glm(density ~ -1 + Mean_hyp, data = GRden, family = poisson)
summary(Grock.glm)
plot(predict(Grock.glm), resid(Grock.glm)) #poor fit
library(effects)
plot(allEffects(Grock.glm))

# make hypoxic classes 
zzz <- GRden %>% 
  select(density, Mean_hyp) %>% 
  mutate(Hypoxia= ifelse(Mean_hyp <= 0.5, "severe_hypoxia",
                      ifelse(Mean_hyp > 0.5 & Mean_hyp <=  1.43,"hypoxic", 
                        ifelse(Mean_hyp > 1.43, "non-hypoxic", NA) ) ))

GRhypox.glm <- glm(density ~ -1 + Hypoxia, data = zzz, family = poisson)
plot(allEffects(GRhypox.glm))
```

# length with hypoxia 
```{r}
Grock.lm <- lm(length_cm ~ -1 + Hypoxia, data = Grock)
hist(resid(Grock.lm), xlab='residuals',main='',col="blue")
summary(Grock.lm)
plot(allEffects(Grock.lm))

plot(Grock$year, resid(Grock.lm)) #poor fit

```

# binomial w/ presence& absence 
```{r}
GRhyp_pres.glm <- glm(Presence ~ -1 + mean_hyp, data = Spe_present, family = binomial)
plot(allEffects(GRhyp_pres.glm))

```

# false positives
```{r}
library(cutpointr)
zzz <- cutpointr(na.omit(Spe_present), mean_hyp, Presence, boot_runs = 100)
zz <- cutpointr(na.omit(Spe_present), mean_hyp, Presence, method = oc_manual, cutpoint = 1.43, boot_runs = 100) #sets cut point at hypoxic threshold
summary(zz)
plot(zzz)
```



